# Camera
BOARD_CAMERA_SENSORS := imx132 imx134 imx135 imx214 imx214_8916
TARGET_USE_VENDOR_CAMERA_EXT := true
USE_DEVICE_SPECIFIC_CAMERA := true
# TARGET_HAS_LEGACY_CAMERA_HAL1 := true
# TARGET_CAMERASERVICE_CLOSES_NATIVE_HANDLES := true
